
services:
  web01:
    build: .
    container_name: web01
    ports:
      - "8081:80"
    networks:
      - jobnet
    volumes:
      - ./nginx/web1.conf:/etc/nginx/conf.d/default.conf:ro
    image: peggy100/job-market-web:latest 
    
      

  web02:
    build: .
    container_name: web02
    ports:
      - "8082:80"
    networks:
      - jobnet
    volumes:
      - ./nginx/web2.conf:/etc/nginx/conf.d/default.conf:ro
    image: peggy100/job-market-web:latest 
  lb:
    image: nginx:alpine
    container_name: job-lb
    depends_on:
      - web01
      - web02
    ports:
      - "8080:80"
    volumes:
      - ./nginx/nginx-lb.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - jobnet

    

networks:
  jobnet:
    driver: bridge
